export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const LOAD_MANUFACTURER_SUCCESS = 'LOAD_MANUFACTURER_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const SORT_PRODUCTS_TITLE_ASC = 'SORT_PRODUCTS_TITLE_ASC';
export const SORT_PRODUCTS_TITLE_DESC = 'SORT_PRODUCTS_TITLE_DESC';

export const SORT_PRODUCTS_MANUFACTURER_ASC = 'SORT_PRODUCTS_MANUFACTURER_ASC';
export const SORT_PRODUCTS_MANUFACTURER_DESC = 'SORT_PRODUCTS_MANUFACTURER_DESC';

export const SORT_PRODUCTS_CATEGORY_ASC = 'SORT_PRODUCTS_CATEGORY_ASC';
export const SORT_PRODUCTS_CATEGORY_DESC = 'SORT_PRODUCTS_CATEGORY_DESC';
